
["Hit Indication Config"]
	#Determines opacity of the indicators.
	#Range: 0 ~ 100
	"Indicator Opacity (0-100)" = 25
	#Determines scale of indicators.
	#Range: 0 ~ 100
	"Indicator Default Scale (0-100)" = 25
	#Determines distance of an indicator from crosshair.
	#Range: > 30
	"Distance From Crosshair" = 30
	#Any instance of damage that deals 30 percent or more of max health will result in larger indicators.
	"Heavy damage makes indicator larger" = false
	#Determines the color of the hit indicator
	"Hit Indicator Color" = "FF0000"
	#Determines the color of the block indicator
	"Block Indicator Color" = "0000FF"
	#Amount of ticks after which indicator disappears.
	#Range: > 0
	"Indicator Fade Rate (Ticks)" = 50
	#The indicators will appear on the edges of your screen instead of near the crosshair
	"Edge of Screen Mode" = true
	#Distance from entity after which indicator starts to become gradually smaller.
	#Range: > 0
	"Distance Scaling Cutoff" = 10
	#Enables hit markers on crit/kill.
	"Enable Crit/Kill Markers" = false
	#Shows red indicator when an entity hits the player with a non-damaging negative potion.
	"Display Hits From Non-Damaging Negative Potions" = false
	#Shows blue indicator when the player blocks incoming damage with a shield.
	"Show Block Indicator" = true
	#Determines maximum indicator count shown on screen (0 = unlimited).
	#Range: > 0
	"Max Indicator Count" = 0
	#Enables hit indication.
	"Enable Hit Indication" = true
	#Shows a special indicator when hit direction can't be determined
	"Enable Non Directional Damage" = false
	#Scale of the indicator depends on the distance
	"Enable Distance Scaling" = true

